# Identificación del proyecto
sonar.projectKey=AlexisYazir_front-sport
sonar.organization=alexisyazir
sonar.host.url=https://sonarcloud.io

# Rutas a analizar
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, **/*.spec.ts, **/*.mock.ts, environments/**

# Lenguaje y configuración
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Archivos adicionales a incluir (HTML templates)
sonar.inclusions=src/**/*.ts, src/**/*.html

# Módulos específicos a analizar (según tu plan de pruebas)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts