import {
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowLeftRight,
  LucideArrowRight,
  LucideArrowUp,
  LucideArrowUpRight,
  LucideAward,
  LucideBadge,
  LucideBadgeCheck,
  LucideBan,
  LucideBanknote,
  LucideBell,
  LucideBrainCircuit,
  LucideBrushCleaning,
  LucideBuilding2,
  LucideCalendar,
  LucideCalendarDays,
  LucideCalendarX,
  LucideChartBar,
  LucideChartLine,
  LucideChartNoAxesCombined,
  LucideChartPie,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronsLeft,
  LucideChevronsRight,
  LucideCircleAlert,
  LucideCircle,
  LucideCircleCheck,
  LucideCircleHelp,
  LucideCircleMinus,
  LucideCirclePlus,
  LucideCircleUser,
  LucideClipboardClock,
  LucideClipboardList,
  LucideCloudOff,
  LucideCloudUpload,
  LucideContact,
  LucideCopy,
  LucideCreditCard,
  LucideDatabase,
  LucideDollarSign,
  LucideDownload,
  LucideDumbbell,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFileSpreadsheet,
  LucideFileText,
  LucideFileUp,
  LucideHeadset,
  LucideHeart,
  LucideHistory,
  LucideHouse,
  LucideIdCard,
  LucideImage,
  LucideImagePlus,
  LucideInbox,
  LucideInfo,
  LucideKeyRound,
  LucideLayoutDashboard,
  LucideLayoutGrid,
  LucideLightbulb,
  LucideLink2,
  LucideListFilter,
  LucideListX,
  LucideLoaderCircle,
  LucideLocateFixed,
  LucideLock,
  LucideLogIn,
  LucideLogOut,
  LucideMail,
  LucideMailCheck,
  LucideMap,
  LucideMapPin,
  LucideMapPinPen,
  LucideMegaphone,
  LucideMenu,
  LucideMessageCircle,
  LucideMessageSquareText,
  LucideMic,
  LucideMinus,
  LucideMonitorSmartphone,
  LucideMoon,
  LucideNavigation,
  LucideNewspaper,
  LucidePackage,
  LucidePackageCheck,
  LucidePalette,
  LucidePenLine,
  LucidePhone,
  LucidePlay,
  LucidePlus,
  LucidePrinter,
  LucideReceiptText,
  LucideRefreshCw,
  LucideRepeat2,
  LucideRotateCcw,
  LucideRotateCcwKey,
  LucideRoute,
  LucideSave,
  LucideSearch,
  LucideSearchX,
  LucideSettings,
  LucideShapes,
  LucideShare2,
  LucideShield,
  LucideShieldCheck,
  LucideShieldKeyhole,
  LucideShoppingBag,
  LucideShoppingCart,
  LucideSlidersHorizontal,
  LucideSquarePlus,
  LucideStar,
  LucideStore,
  LucideSun,
  LucideTable2,
  LucideTag,
  LucideTags,
  LucideThumbsUp,
  LucideTrash2,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideTruck,
  LucideUnlink2,
  LucideUpload,
  LucideUser,
  LucideUserCheck,
  LucideUserPlus,
  LucideUserRoundX,
  LucideUsers,
  LucideWalletCards,
  LucideWallpaper,
  LucideX,
  LucideZap,
  type LucideIcon,
  type LucideIconData,
} from '@lucide/angular';

const aliasIcon = (name: string, icon: LucideIcon): LucideIconData => ({
  ...icon.icon,
  name,
});

const iconAliases: Record<string, LucideIcon> = {
  account_balance_wallet: LucideWalletCards,
  account_circle: LucideCircleUser,
  add: LucidePlus,
  add_box: LucideSquarePlus,
  add_circle: LucideCirclePlus,
  add_photo_alternate: LucideImagePlus,
  add_shopping_cart: LucideShoppingCart,
  analytics: LucideChartNoAxesCombined,
  arrow_back: LucideArrowLeft,
  arrow_down: LucideArrowDown,
  arrow_forward: LucideArrowRight,
  arrow_up: LucideArrowUp,
  article: LucideFileText,
  attach_money: LucideDollarSign,
  auto_delete: LucideTrash2,
  backup: LucideDatabase,
  badge: LucideIdCard,
  bar_chart: LucideChartBar,
  block: LucideBan,
  bolt: LucideZap,
  brand_awareness: LucideMegaphone,
  brand_family: LucideTags,
  branding_watermark: LucideBadge,
  business: LucideBuilding2,
  calendar_month: LucideCalendarDays,
  calendar_today: LucideCalendar,
  call: LucidePhone,
  category: LucideShapes,
  chat: LucideMessageCircle,
  check: LucideCheck,
  check_circle: LucideCircleCheck,
  chevron_left: LucideChevronLeft,
  chevron_right: LucideChevronRight,
  cleaning_services: LucideBrushCleaning,
  close: LucideX,
  cloud_off: LucideCloudOff,
  cloud_upload: LucideCloudUpload,
  compare_arrows: LucideArrowLeftRight,
  contact_mail: LucideContact,
  content_copy: LucideCopy,
  dark_mode: LucideMoon,
  dashboard: LucideLayoutDashboard,
  database: LucideDatabase,
  dataset: LucideTable2,
  delete: LucideTrash2,
  delete_sweep: LucideTrash2,
  description: LucideFileText,
  devices: LucideMonitorSmartphone,
  do_not_disturb_on: LucideCircleMinus,
  domain: LucideBuilding2,
  donut_large: LucideChartPie,
  download: LucideDownload,
  edit: LucidePenLine,
  edit_location_alt: LucideMapPinPen,
  edit_note: LucidePenLine,
  error: LucideCircleAlert,
  event_busy: LucideCalendarX,
  expand_more: LucideChevronDown,
  favorite: LucideHeart,
  fiber_new: LucideBadge,
  file_download: LucideDownload,
  filter_alt: LucideListFilter,
  filter_alt_off: LucideListX,
  first_page: LucideChevronsLeft,
  grid_view: LucideLayoutGrid,
  group: LucideUsers,
  group_add: LucideUserPlus,
  group_off: LucideUserRoundX,
  groups: LucideUsers,
  help: LucideCircleHelp,
  help_center: LucideCircleHelp,
  history: LucideHistory,
  home: LucideHouse,
  how_to_reg: LucideUserCheck,
  image: LucideImage,
  inbox: LucideInbox,
  info: LucideInfo,
  inventory: LucidePackageCheck,
  inventory_2: LucidePackage,
  last_page: LucideChevronsRight,
  light_mode: LucideSun,
  lightbulb: LucideLightbulb,
  link: LucideLink2,
  link_off: LucideUnlink2,
  local_fire_department: LucideTag,
  local_offer: LucideTag,
  local_shipping: LucideTruck,
  location_on: LucideMapPin,
  lock: LucideLock,
  lock_clock: LucideClipboardClock,
  lock_person: LucideShieldKeyhole,
  lock_reset: LucideRotateCcwKey,
  login: LucideLogIn,
  logout: LucideLogOut,
  mail: LucideMail,
  mail_lock: LucideShieldKeyhole,
  map: LucideMap,
  mark_email_unread: LucideMailCheck,
  menu: LucideMenu,
  model_training: LucideBrainCircuit,
  monitoring: LucideChartLine,
  moving: LucideTrendingUp,
  my_location: LucideLocateFixed,
  navigation: LucideNavigation,
  north_east: LucideArrowUpRight,
  notifications: LucideBell,
  open_in_new: LucideExternalLink,
  orders: LucideClipboardList,
  package_2: LucidePackage,
  palette: LucidePalette,
  password: LucideKeyRound,
  payments: LucideBanknote,
  pending: LucideClipboardClock,
  pending_actions: LucideClipboardClock,
  people: LucideUsers,
  person: LucideUser,
  person_add: LucideUserPlus,
  person_off: LucideUserRoundX,
  phone: LucidePhone,
  play_arrow: LucidePlay,
  policy: LucideShieldCheck,
  print: LucidePrinter,
  progress_activity: LucideLoaderCircle,
  query_stats: LucideChartNoAxesCombined,
  radio_button_unchecked: LucideCircle,
  rate_review: LucideMessageSquareText,
  receipt_long: LucideReceiptText,
  refresh: LucideRefreshCw,
  remove: LucideMinus,
  remove_shopping_cart: LucideShoppingCart,
  repeat: LucideRepeat2,
  replay: LucideRotateCcw,
  restart_alt: LucideRotateCcw,
  reviews: LucideMessageSquareText,
  route: LucideRoute,
  save: LucideSave,
  schedule: LucideCalendar,
  search: LucideSearch,
  search_off: LucideSearchX,
  security: LucideShieldCheck,
  sell: LucideTag,
  settings: LucideSettings,
  settings_voice: LucideMic,
  share: LucideShare2,
  shield: LucideShield,
  shield_lock: LucideShieldKeyhole,
  shopping_bag: LucideShoppingBag,
  shopping_cart: LucideShoppingCart,
  shopping_cart_checkout: LucideShoppingCart,
  sort: LucideListFilter,
  sports: LucideDumbbell,
  star: LucideStar,
  storage: LucideDatabase,
  storefront: LucideStore,
  support_agent: LucideHeadset,
  sync: LucideRefreshCw,
  table_chart: LucideTable2,
  task_alt: LucideCircleCheck,
  thumb_up: LucideThumbsUp,
  tips_and_updates: LucideLightbulb,
  trending_up: LucideTrendingUp,
  tune: LucideSlidersHorizontal,
  upload: LucideUpload,
  upload_file: LucideFileUp,
  verified: LucideBadgeCheck,
  verified_user: LucideShieldCheck,
  visibility: LucideEye,
  visibility_off: LucideEyeOff,
  wallpaper: LucideWallpaper,
  warning: LucideTriangleAlert,
  workspace_premium: LucideAward,
};

export const SPORT_CENTER_ICONS = Object.entries(iconAliases).map(([name, icon]) => aliasIcon(name, icon));
